/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("com.example.greeter.java-application-conventions")
    alias(libs.plugins.boot)
}

dependencies {
    implementation(platform(libs.spring.boot.dependencies))
    implementation("org.apache.commons:commons-text")
    implementation(project(":utilities"))
}

application {
    // Define the main class for the application.
    mainClass.set("com.example.greeter.app.App")
}
